### ISSUE TITLE
Need at least node 7.5 for sonos2mqtt to work

### ISSUE THREAD

**Issue by Eggn1n3** [svrooij/sonos2mqtt#1]
Hi,

I had some problems running sonos2mqtt on node v6. I got error message listed below:

pi@raspberry2:~ $ node  ./sonos_test.js 
/home/pi/node_modules/sonos/lib/sonos.js:66
  var implicitListen = async function (event, listener) {
                                          ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/node_modules/sonos/index.js:1:80)
    at Module._compile (module.js:570:32)
pi@raspberry2:~ $ node -v
v6.10.0

When I upgraded to node 9 it all worked. Seems this is related to async package that at least needs node 7.5

**Comment by svrooij** [comment]
you where right that should be in the readme. Like it is now 👍 

You enjoy using this bridge?

**Comment by Eggn1n3** [comment]
This bridge works great, I love it!
One question though: when you send a "pause"command to a Sonos device you get an event that the device has been stopped instead of paused. Is that correct?

**Comment by svrooij** [comment]
Apperantly it depends on what’s playing.
If you’re playing TuneIN you cannot pause, since it is live. Playing Spotify would allow you to pause the music.

**Comment by Eggn1n3** [comment]
You  are absolutely right! I was indeed using TuneIn. Using spotify shows the state "paused".
Thanks for your quick response.
