### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 's:Body')

### ISSUE THREAD

**Issue by Reinschki** [svrooij/sonos2mqtt#189]
Hello, 
i am using sonos2mqtt together with Fhem.
A publish with /cmd/ generally fails.
As an example, I show below the logging after the publish sonos/cmd/pauseall.

What is going wrong?

```
2023-01-19T11:01:13.597Z [Information] LogLevel changed to verbose
2023-01-19T11:01:48.656Z [Debug] Mqtt got generic command pauseall
2023-01-19T11:01:48.656Z [Debug] Got generic command pauseall from mqtt
/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/base-service.js:226
            if (typeof errorResponse['s:Envelope']['s:Body']['s:Fault'] !== 'undefined') {
                                                  ^
TypeError: Cannot read properties of undefined (reading 's:Body')
    at AVTransportService.handleErrorResponse (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/base-service.js:226:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AVTransportService.handleRequest (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/base-service.js:188:16)
    at async AVTransportService.SoapRequestWithBodyNoResponse (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/base-service.js:123:16)
    at async AVTransportService.Pause (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/av-transport.service.js:169:53)
    at async SonosDevice.Pause (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/sonos-device.js:938:28)
    at async Promise.all (index 1)
Node.js v17.3.0
2023-01-19T11:01:49.315Z [Information] Starting sonos2mqtt v3.2.0
2023-01-19T11:01:49.324Z [Information] LogLevel changed to information
2023-01-19T11:01:49.399Z [Information] Found 7 sonos speakers
2023-01-19T11:01:49.426Z [Information] Mqtt connection changed to connected: true
```
Regards
Reiner

**Comment by svrooij** [comment]
can you try with any of the new beta versions? Like `3.2.0-beta.9`

**Comment by Reinschki** [comment]
```
2023-01-20T06:30:49.642Z [Information] Starting sonos2mqtt v3.2.0-beta.9
2023-01-20T06:30:49.654Z [Information] LogLevel changed to information
2023-01-20T06:30:49.676Z [Information] Found 7 sonos speakers
2023-01-20T06:30:49.707Z [Information] Mqtt connection changed to connected: true
2023-01-20T06:31:59.374Z [Information] Shutdown sonos2mqtt, please wait.
2023-01-20T06:31:59.405Z [Information] Mqtt connection changed to connected: false
2023-01-20T06:32:01.013Z [Information] Starting sonos2mqtt v3.2.0-beta.9
2023-01-20T06:32:01.023Z [Information] LogLevel changed to information
2023-01-20T06:32:01.078Z [Information] Found 7 sonos speakers
2023-01-20T06:32:01.117Z [Information] Mqtt connection changed to connected: true
2023-01-20T06:32:45.350Z [Information] LogLevel changed to verbose
2023-01-20T06:33:01.759Z [Verbose] Publishing state for RINCON_542A1BBE498001400
2023-01-20T06:33:01.759Z [Verbose] Mqtt publish to sonos/RINCON_542A1BBE498001400 [object Object]
2023-01-20T06:33:02.575Z [Debug] Mqtt got generic command pauseall
2023-01-20T06:33:02.575Z [Debug] Got generic command pauseall from mqtt
/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/base-service.js:237
            if (typeof errorResponse['s:Envelope']['s:Body']['s:Fault'] !== 'undefined') {
                                                  ^
TypeError: Cannot read properties of undefined (reading 's:Body')
    at AVTransportService.handleErrorResponse (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/base-service.js:237:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AVTransportService.handleRequest (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/base-service.js:199:16)
    at async AVTransportService.SoapRequestWithBodyNoResponse (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/base-service.js:133:16)
    at async AVTransportService.Pause (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/av-transport.service.js:169:53)
    at async SonosDevice.Pause (/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/sonos-device.js:976:28)
    at async Promise.all (index 1)
2023-01-20T06:33:03.449Z [Information] Starting sonos2mqtt v3.2.0-beta.9
2023-01-20T06:33:03.457Z [Information] LogLevel changed to information
2023-01-20T06:33:03.489Z [Information] Found 7 sonos speakers
2023-01-20T06:33:03.519Z [Information] Mqtt connection changed to connected: true

```
